/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:45:40 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _UISettingsKeyPathObserver <NSObject>
@required
-(void)settings:(id)arg1 changedValueForKeyPath:(id)arg2;

@end

