/*
                       * This header is generated by classdump-dyld 0.1
                       * on Wednesday, September 17, 2014 at 8:28:10 PM Eastern European Summer Time
                       * Operating System: Version 8.0 (Build 12A365)
                       * Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
                       * classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
                       */


@protocol SBReachabilityTriggerDelegate <NSObject>
@required
-(void)triggerDidTriggerReachability:(id)arg1;
@end

