/*
                       * This header is generated by classdump-dyld 0.1
                       * on Wednesday, September 17, 2014 at 8:28:10 PM Eastern European Summer Time
                       * Operating System: Version 8.0 (Build 12A365)
                       * Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
                       * classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
                       */

#import "SBReachabilityTriggerDelegate.h"

@class NSMutableSet, NSTimer, SBReachabilityTrigger, NSString;

@interface SBReachabilityManager : NSObject <SBReachabilityTriggerDelegate> {

	NSMutableSet* _observers;
	BOOL _keepAliveForEndedInteraction;
	BOOL _reachabilityModeActive;
	BOOL _reachabilityModeEnabled;
	NSTimer* _keepAliveTimer;
	NSMutableSet* _temporaryDisabledReasons;
	SBReachabilityTrigger* _trigger;

}

@property (nonatomic,readonly) BOOL reachabilityModeActive;           //@synthesize reachabilityModeActive=_reachabilityModeActive - In the implementation block
@property (assign,nonatomic) BOOL reachabilityEnabled; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString* description; 
@property (copy,readonly) NSString* debugDescription; 
+(BOOL)reachabilitySupported;
+(id)sharedInstance;
-(void)_handleReachabilityActivated;
-(void)_handleReachabilityDeactivated;
-(void)_handleSignificantTimeChanged;
-(void)_clearKeepAliveTimer;
-(void)_updateReachabilityModeActive:(BOOL)arg1 withRequestingObserver:(id)arg2 ;
-(BOOL)reachabilityModeActive;
-(void)_setKeepAliveTimerForDuration:(double)arg1 ;
-(void)cancelPendingReachabilityRequests;
-(void)deactivateReachabilityModeForObserver:(id)arg1 ;
-(void)_notifyObserversReachabilityModeActive:(BOOL)arg1 excludingObserver:(id)arg2 ;
-(void)_toggleReachabilityModeWithRequestingObserver:(id)arg1 ;
-(void)_keepAliveTimerFired:(id)arg1 ;
-(void)triggerDidTriggerReachability:(id)arg1 ;
-(void)disableExpirationTimerForInteraction;
-(void)enableExpirationTimerForEndedInteraction;
-(BOOL)reachabilityEnabled;
-(void)setReachabilityEnabled:(BOOL)arg1 ;
-(void)setReachabilityTemporarilyDisabled:(BOOL)arg1 forReason:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)removeObserver:(id)arg1 ;
-(void)addObserver:(id)arg1 ;
@end

